### ISSUE TITLE
Reload Timer on Frontend Broken

### ISSUE THREAD

**Issue by e2m32** [e2m32/hass_custom_timer#6]
@e2m32 The error only occurs if I reload the timer in the frontend.
```
timer:
  zahnburste_ladetimer:
    name: Zahnbürste  Ladetimer
    duration: '30:00:00'
    icon: mdi:timer-sand
    restore: true
    restore_grace_period: '00:15:00'
  ventilator_timer:
    name: Ventilator Timer
    icon: mdi:camera-timer
    restore: true
    restore_grace_period: '00:15:00'
```

_Originally posted by @Krocko in https://github.com/e2m32/hass_custom_timer/issues/5#issuecomment-795416678_
